### ISSUE TITLE
Alternatives to POP3 

### ISSUE THREAD

**Issue by bmercernccer** [wagesj45/gray-duck-mail#3]
POP3 is becoming harder to use as more providers move away from it. 
Are there any plans to support alternatives?

**Comment by wagesj45** [comment]
I'll check the code and more specifically the mail library to see what protocols are supported. Is there a particular protocol that your email provider does support that isn't POP3?

I originally chose POP3 since it seems to be universally supported, being one of the oldest protocols. I'd be interested in which providers aren't supporting it anymore.

**Comment by wagesj45** [comment]
So I checked, @bmercernccer, and it seems that I should be able to fairly painlessly be able to add IMAP support as it is included in [MailKit](https://github.com/jstedfast/MailKit). I'll have to add a couple of docker environment variables to the configuration, but shouldn't be too bad.

**Comment by wagesj45** [comment]
@bmercernccer I have pushed a test build of the docker image to [the `:testing` tag](https://hub.docker.com/r/wagesj45/gray-duck-mail/tags). If you'd like to help, I suggest exporting your database (in the Administration) page, then recreating the container using `docker pull wagesj45/gray-duck-mail:testing`. Two additional environment variables should be accepted: `EMAIL_PROTOCOL` and `IMAP_FOLDER`. `EMAIL_PROTOCOL` can be either `POP3` or `IMAP`. You'll probably want to keep `IMAP_FOLDER` at its default value of `INBOX` unless you have a special configuration.

If successful, the version at the footer of the page should read `0.9.9.0` and IMAP connections should work. If there are any errors in the Docker logs, posting them here would greatly help me in debugging.
