### ISSUE TITLE
Using hashes for lists and contacts to secure unsubscribe link

### ISSUE THREAD

**Issue by es86de** [wagesj45/gray-duck-mail#7]
The format of the unsubscribe link is "http[s]://hostname/Unsubscribe/{contactID}/{discussionListID}". This might cause manipulation. It would be more secure to generate hashes for the contacts and lists, and use these hashes instead. Just a suggestion.

**Comment by wagesj45** [comment]
I did consider this when implementing the quick unsubscribe functionality. I was hoping to avoid a system that would require storing additional data, like a precomputed unique hash, since this would require additional database migration steps. Otherwise, any hash would be based on known information. Obfuscation might keep script kiddies from executing simple attacks, so I think this is worth doing.

**Comment by vakabus** [comment]
Hi, just passing by and I've noticed this issue. I might have a solution for you that does not involve database migrations.

I think you could solve the issue by signing the URL using authenticated hashes. That would require storing only a single secret key. To give a more specific example, a possibility would be to use URLs like this:

`http[s]://hostname/Unsubscribe/{contactID}/{discussionListID}/sha256/{hmac_sha256(key, contactID, discussionListID})}`

When opening the link:
1. take `contactID` and `discussionListID` from the URL
2. calculate `hmac_sha256(key, contactID, discussionListID})`
3. compare and accept/reject request

You can make the hash at the end of the URL as short as you want (use only first couple of bits of the hash) depending on how resistant you want to be to brute-force attacks. I believe that for example 32 bits should be enough in this case, maybe even less. I wouldn't worry too much about attacks here, it should just prevent anyone from messing with it too much.

Feel free to ignore the suggestion :wink:. I just have it on my mind because I've been recently working on a database-less utility for file sharing which uses this technique.

**Comment by wagesj45** [comment]
@vakabus I think this is a wonderful solution and fits with the project's minimalist design goals. This will be the implementation when I tackle this issue. I truly thank you for the idea.
